module.exports = {
    "bus": ["buses","busses"],
    "wish": ["wishes"],
    "pitch": ["pitches"],
    "box": ["boxes"],
    "penny": ["pennies"],
    "spy": ["spies"],
    "baby": ["babies"],
    "city": ["cities"],
    "daisy": ["daisies"],
    "woman": ["women"],
    "man": ["men"],
    "child": ["children"],
    "tooth": ["teeth"],
    "foot": ["feet"],
    "person": ["people"],
    "leaf": ["leaves"],
    "mouse": ["mice"],
    "goose": ["geese"],
    "half": ["halves"],
    "knife": ["knives"],
    "wife": ["wives"],
    "life": ["lives"],
    "elf": ["elves"],
    "loaf": ["loaves"],
    "potato": ["potatoes"],
    "tomato": ["tomatoes"],
    "cactus": ["cacti"],
    "focus": ["foci","focuses"],
    "fungus": ["fungi","funguses"],
    "nucleus": ["nuclei"],
    "syllabus": ["syllabi","syllabuses"],
    "analysis": ["analyses"],
    "diagnosis": ["diagnoses"],
    "oasis": ["oases"],
    "thesis": ["theses"],
    "crisis": ["crises"],
    "phenomenon": ["phenomena"],
    "criterion": ["criteria"],
    "datum": ["data"],
    "kiss": ["kisses"],
    "word": ["words"],
    "apple": ["apples"],
    "book": ["books"],
    "page": ["pages"],
    "abyss": ["abysses"],
    "alumnus": ["alumni"],
    "aquarium": ["aquaria","aquariums"],
    "arch": ["arches"],
    "atlas": ["atlases"],
    "axe": ["axes"],
    "bacterium": ["bacteria"],
    "batch": ["batches"],
    "beach": ["beaches"],
    "brush": ["brushes"],
    "calf": ["calves"],
    "chateau": ["chateaux","chateaus"],
    "cherry": ["cherries"],
    "church": ["churches"],
    "circus": ["circuses"],
    "copy": ["copies"],
    "curriculum": ["curricula"],
    "dictionary": ["dictionaries"],
    "domino": ["dominoes"],
    "dwarf": ["dwarves","dwarfs"],
    "echo": ["echoes"],
    "emphasis": ["emphases"],
    "family": ["families"],
    "fax": ["faxes"],
    "flush": ["flushes"],
    "fly": ["flies"],
    "hero": ["heroes"],
    "hippopotamus": ["hippopotami","hippopotamuses"],
    "hoax": ["hoaxes"],
    "hoof": ["hooves"],
    "index": ["indexes","indices","indeces"],
    "iris": ["irises"],
    "lady": ["ladies"],
    "mango": ["mangoes"],
    "mess": ["messes"],
    "motto": ["mottoes"],
    "nanny": ["nannies"],
    "neurosis": ["neuroses"],
    "octopus": ["octopi","octopuses"],
    "party": ["parties"],
    "pass": ["passes"],
    "plateau": ["plateaux","plateaus"],
    "poppy": ["poppies"],
    "quiz": ["quizzes"],
    "reflex": ["reflexes"],
    "scarf": ["scarves","scarfs"],
    "scratch": ["scratches"],
    "sheaf": ["sheaves"],
    "shelf": ["shelves"],
    "son-in-law": ["sons-in-law"],
    "splash": ["splashes"],
    "stitch": ["stitches"],
    "story": ["stories"],
    "tax": ["taxes"],
    "thief": ["thieves"],
    "tornado": ["tornadoes"],
    "try": ["tries"],
    "volcano": ["volcanoes"],
    "waltz": ["waltzes"],
    "wash": ["washes"],
    "watch": ["watches"],
    "wharf": ["wharves"],
    "addendum": ["addenda"],
    "alga": ["algae"],
    "alumna": ["alumnae"],
    "antenna": ["antennas"],
    "apparatus": ["apparatuses"],
    "appendix": ["appendices","appendixes"],
    "axis": ["axes"],
    "bacillus": ["bacilli"],
    "basis": ["bases"],
    "beau": ["beaux"],
    "buffalo": ["buffalos","buffaloes"],
    "bureau": ["bureaus","bureaux"],
    "corps": ["corps"],
    "corpus": ["corpora","corpuses"],
    "die": ["dice"],
    "ellipsis": ["ellipses"],
    "embargo": ["embargoes"],
    "erratum": ["errata"],
    "fireman": ["firemen"],
    "fish": ["fishes"],
    "formula": ["formulas","formulae"],
    "genus": ["genera"],
    "hypothesis": ["hypotheses"],
    "louse": ["lice"],
    "matrix": ["matrices","matrixes"],
    "medium": ["media"],
    "memorandum": ["memoranda"],
    "millennium": ["millenniums","millennium","millennia"],
    "moose": ["moose"],
    "mosquito": ["mosquitoes"],
    "nebula": ["nebulae","nebulas"],
    "ovum": ["ova"],
    "ox": ["oxen"],
    "paralysis": ["paralyses"],
    "parenthesis": ["parentheses"],
    "radius": ["radii"],
    "self": ["selves"],
    "stimulus": ["stimuli"],
    "stratum": ["strata"],
    "symposium": ["symposia","symposiums"],
    "synthesis": ["syntheses"],
    "synopsis": ["synopses"],
    "tableau": ["tableaux","tableaus"],
    "that": ["those"],
    "this": ["these"],
    "torpedo": ["torpedoes"],
    "vertebra": ["vertebrae"],
    "veto": ["vetoes"],
    "vita": ["vitae"],
    "wolf": ["wolves"],
    "zero": ["zeros","zeroes"],
    "agendum": ["agenda"],
    "agent-provocateur": ["agents-provocateurs"],
    "aide-de-camp": ["aides-de-camp"],
    "anathema": ["anathemata"],
    "attorne-general": ["attorneys-general"],
    "beau-geste": ["beaux-gestes"],
    "bel-homme": ["beaux-hommes"],
    "belle-epoque": ["belles-epoques","belle-epoques"],
    "bildungsroman": ["bildungsromane"],
    "bill-of-attainder": ["bills-of-attainder"],
    "biscotto": ["biscotti"],
    "bon-mot": ["bons-mots"],
    "bon-vivant": ["bons-vivants"],
    "brother": ["brothers"],
    "candelabrum": ["candelabra"],
    "canto": ["cantos"],
    "cat-o'-nine-tails": ["cat-o'-nine-tails"],
    "chick": ["chicks"],
    "chicken": ["chickens"],
    "cod": ["cods"],
    "coup d'etat": ["coups d'etat"],
    "court-martial": ["courts-martial"],
    "cri du coeur": ["cris du coeur"],
    "director-general": ["directors-general"],
    "dogma": ["dogmata"],
    "dukhobor": ["dukhobortsy"],
    "entente-cordiale": ["ententes-cordiales"],
    "fait-accompli": ["faits-accomplis"],
    "fee simple absolute": ["fees simple absolute"],
    "gens": ["gentes"],
    "genu": ["genua"],
    "governor-general": ["governors-general"],
    "graffito": ["graffiti"],
    "hallux": ["halluces"],
    "ham on rye": ["ham-on-ryes"],
    "head of state": ["heads of states","heads of state"],
    "hetero": ["heteros"],
    "holluschik": ["holluschikie"],
    "idee-fixe": ["idees-fixes"],
    "insigne": ["insignia"],
    "iter": ["itinera"],
    "jack-in-the-box": ["jacks-in-the-box","jack-in-the-boxes"],
    "jack-in-the-pulpit": ["jacks-in-the-pulpit","jack-in-the-pulpits"],
    "jack-o'-lantern": ["jack-o'-lanterns"],
    "kimono": ["kimonos"],
    "krone": ["kroner"],
    "lemma": ["lemmata","lemmas"],
    "man-about-town": ["men-about-town"],
    "man-child": ["men-children"],
    "man-of-war": ["men-of-war"],
    "manservant": ["menservants"],
    "matzo": ["matzoth"],
    "minister-president": ["ministers-president"],
    "never-was": ["never-weres"],
    "opus": ["opera","operas"],
    "ornis": ["ornithes"],
    "panino": ["panini"],
    "paparazzo": ["paparazzi"],
    "passerby": ["passersby"],
    "piano": ["pianos"],
    "portico": ["porticos"],
    "pro": ["pros"],
    "procurator-fiscal": ["procurators-fiscal"],
    "quadrans": ["quadrantes"],
    "quarto": ["quartos"],
    "rubai": ["rubaiyat"],
    "runner-up": ["runners-up"],
    "schema": ["schemata","schemas"],
    "scrotum": ["scrota","scrotums"],
    "seraph": ["seraphim"],
    "ship of the line": ["ships of the line"],
    "shtetl": ["shtetlach"],
    "son of a bitch": ["sons of bitches","sons-of-a-bitch"],
    "spaghetto": ["spaghettis","spaghetti"],
    "stigma": ["stigmata","stigmas"],
    "stoma": ["stomata","stomas"],
    "tete-a-tete": ["tete-a-tetes"],
    "torte": ["torten"],
    "tour-de-force": ["tours-de-force"],
    "ushabti": ["ushabtiu"],
    "vas": ["vasa"],
    "will-o'-the-wisp": ["will-o'-the-wisps"],
    "woman-doctor": ["women-doctors"],
    "wunderkind": ["wunderkinder"],
    "yeshiva": ["yeshivoth"],
    "zecchino": ["zecchini"],
    "amoeba": ["amoebae"],
    "larva": ["larvae"],
    "barracks": ["barracks"],
    "gas": ["gases"],
    "ass": ["asses"],
    "des": ["deses"],
    "gallows": ["gallows"],
    "aircraft": ["aircraft"],
    "antithesis": ["antitheses"],
    "apex": ["apices","apexes"],
    "château": ["châteaux","châteaus"],
    "codex": ["codices"],
    "concerto": ["concerti","concertos"],
    "faux-pas": ["faux-pas"],
    "fez": ["fezzes","fezes"],
    "grouse": ["grouses"],
    "libretto": ["libretti","librettos"],
    "locus": ["loci"],
    "minutia": ["minutiae"],
    "phylum": ["phyla"],
    "prognosis": ["prognoses"],
    "referendum": ["referenda","referendums"],
    "salmon": ["salmons"],
    "shrimp": ["shrimps"],
    "trout": ["trouts"],
    "tuna": ["tunas"],
    "vertex": ["vertices","vertexes"],
    "vortex": ["vortices","vortexes"],
    "workman": ["workmen"],
    "schoolchild": ["schoolchildren"],
    "belief":["beliefs"],
    "chief":["chiefs"], 
    "grief":["griefs"], 
    "gulf":["gulfs"], 
    "handkerchief":["handkerchiefs"], 
    "kerchief":["kerchiefs"], 
    "mischief":["mischiefs"], 
    "muff":["muffs"], 
    "oaf":["oafs"], 
    "proof":["proofs"], 
    "roof":["roofs"], 
    "safe":["safes"], 
    "turf":["turfs"],
    "albino":["albinos"],
    "armadillo":["armadillos"],
    "auto":["autos"],
    "cameo":["cameos"],
    "cello":["cellos"],
    "combo":["combos"],
    "duo":["duos"],
    "ego":["egos"],
    "folio":["folios"],
    "halo":["halos"],
    "inferno":["infernos"],
    "lasso":["lassos"],
    "memento":["mementos"],
    "memo":["memos"],
    "photo":["photos"],
    "portfolio":["portfolios"],
    "pro":["pros"],
    "silo":["silos"],
    "solo":["solos"],
    "stereo":["stereos"],
    "studio":["studios"],
    "taco":["tacos"],
    "tattoo":["tattoos"],
    "tuxedo":["tuxedos"],
    "typo":["typos"],
    "video":["videos"],
    "yo":["yos"],
    "zoo":["zoos"],
    "abacus":["abacuses"],
    "crocus":["crocuses"],
    "rhombus":["rhombuses"],
    "walrus":["walruses"],
    "pupa":["pupae"],
    "agenda":["agendas"],
    "alfalfa":["alfalfas"],
    "aurora":["auroras"],
    "banana":["bananas"],
    "barracuda":["barracudas"],
    "cornea":["corneas"],
    "nova":["novas"],
    "phobia":["phobias"],
    "album":["albums"],
    "stadium":["stadiums"],
    "alfalfa":["alfalfas"],
    "aurora":["auroras"],
    "banana":["bananas"],
    "barracuda":["barracudas"],
    "cornea":["corneas"],
    "phobia":["phobias"],
    "balloon":["balloons"],
    "carton":["cartons"],
    "annex":["annexes"],
    "complex":["complexes"],
    "duplex":["duplexes"],
    "hex":["hexes"],
    "guru":["gurus"],
    "menu":["menus"],
    "snafu":["snafus"],
    "mussolini":["mussolinis"],
    "pakistani":["pakistanis"],
    "yemeni":["yemenis"],
    "bikini":["bikinis"],
    "martini":["martinis"]
};